### ISSUE TITLE
Improve code quality by importing express and ejs module

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Animesh606/WeatherForcasting#10]
Whole backend code is written using http createServer i can upgrade it to express.

Please assign this to me under JWOC'24

**Comment by Animesh606** [comment]
@Divyanshgarg-04 It is a great issue. Add EJS and express to the project. You are assigned this issue

**Comment by Animesh606** [comment]
The issue is resolved by @Divyanshgarg-04 with pull request #12
