### ISSUE TITLE
Handle the error messages by a alert interface in bottom

### ISSUE THREAD

**Issue by Animesh606** [Animesh606/WeatherForcasting#16]
The error messages are shown like wrong city and other issues
Show like toaster in bottom site of web page.

**Comment by Jenis07** [comment]
Can you assign me this issue under JWOC 2024?

**Comment by Jenis07** [comment]
![image](https://github.com/Animesh606/WeatherForcasting/assets/100338684/eaad17b7-7cd4-40a6-aa4f-6ecccce4b666)
is this good sir?

**Comment by Jenis07** [comment]
![image](https://github.com/Animesh606/WeatherForcasting/assets/100338684/eb694fde-2914-4374-a3f6-b1dec9d8e9e5)
this is for second error ...

**Comment by Animesh606** [comment]
Great! @Jenis07
