### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Animesh606** [Animesh606/WeatherForcasting#7]
Write a proper document which describe :
-> Details about this project.
-> Process of contribution to the project in JWOC
-> How to start the project / Build and run the web application
-> And other relavant info as per your thoughts

**Comment by aniket-1206** [comment]
hey @Animesh606 pls assign this to me for JWOC

**Comment by Animesh606** [comment]
Hey @aniket-1206 as per your request you are assigned this issue to resolve.
You will get one day as it's a easy issue.
