### ISSUE TITLE
Add UI interface with project logo, favicon

### ISSUE THREAD

**Issue by Animesh606** [Animesh606/WeatherForcasting#8]
Make a proper interface as web template with project logo as **WeatherForcasting**
And also a favicon to the project same as logo

Don't need to change any inner content of the project.

**Comment by rakesh-paulraj** [comment]
i would like to work on the issue under JWOC

**Comment by Divyanshgarg-04** [comment]
@Animesh606 I would love to work on this issue under JWOC. Please assign this issue to me

**Comment by avanimehta11** [comment]
@Animesh606 I would like to work on this issue under JWOC'24.

**Comment by ayesha-2101** [comment]
@Animesh606 I would like to work on this under JWOC

**Comment by Animesh606** [comment]
@rakesh-paulraj you were assigned the issue 2 days ago. Have you done with it? Just inform updates.

**Comment by rakesh-paulraj** [comment]
Just working on my other jwoc issues can ,i haven't started it yet can i get some time please

**Comment by Animesh606** [comment]
@rakesh-paulraj you can take one day more as per the rules..
Otherwise the next one got a chance

**Comment by Animesh606** [comment]
Thise issue is solved by @rakesh-paulraj with PR #15

**Comment by rakesh-paulraj** [comment]
Thank you so much
