### ISSUE TITLE
Improve the main box design, add more info and handle more type of weather

### ISSUE THREAD

**Issue by Animesh606** [Animesh606/WeatherForcasting#9]
Make a better design as per your design skill.
Add more information like air pressure, humidity etc.
Add other type of weather also other than cloud, haze, rain etc which are already given.

**Comment by prasukjain07** [comment]
Hey mentor please assign this issue to me under JWoC

**Comment by Divyanshgarg-04** [comment]
@Animesh606  I would love to work on this issue under JWOC'24. Please assign it to me

**Comment by swetasingh8844** [comment]
@Animesh606  please assign this issue to me under jWOC'24.

**Comment by avanimehta11** [comment]
@Animesh606 I would like to contribute to this issue under JWOC'24

**Comment by Animesh606** [comment]
@prasukjain07 this issue was assigned to you 3 days ago. Give any update about this.

**Comment by prasukjain07** [comment]
@Animesh606 Sorry I am not able to do, please un assign me

**Comment by swetasingh8844** [comment]
@Animesh606 please assign to me under jwoc'24

**Comment by Animesh606** [comment]
@Divyanshgarg-04 Will you want to solve this issue  now?

**Comment by Divyanshgarg-04** [comment]
I would love to work on this issue

**Comment by Animesh606** [comment]
Ok @Divyanshgarg-04 take a pull of the latest commits and as the ui design of the project have already developed it is a Medium issue now. All the best

**Comment by Divyanshgarg-04** [comment]
@Animesh606 Unable to clone this project
